version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: symfony-mysql
    environment:
      # Mot de passe root MySQL (uniquement pour l'administration)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}

      # Nom de la base de données
      MYSQL_DATABASE: ${MYSQL_DATABASE:-rfss}

      # Utilisateur "non-root" pour l'application
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_pass}

    volumes:
      - mysql_data:/var/lib/mysql:rw

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
