services:
  mysql:
    image: mysql:8.0
    container_name: symfony-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: always

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony-php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini  # Seulement le fichier de config PHP
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    restart: always

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "8101:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Seulement le fichier de config Nginx
    depends_on:
      - php
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
    restart: always

volumes:
  mysql_data:
