services:
  php:
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: "mysql://app:app_pass@mysql:3306/rfess?serverVersion=8.0"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
  nginx:
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
