services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony-php
    volumes:
      - .:/var/www/html:rw,cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      SYMFONY_ENV: dev
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    ports:
      - "8101:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html:rw,cached
    depends_on:
      - php
