services:
  php:
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: "mysql://app:app_pass@mysql:3306/rfess?serverVersion=8.0"
    volumes: []  # Pas de volumes en prod : le code est copié dans l'image pour plus de sécurité
    ports:
      - "9000:9000"

  nginx:
    ports:
      - "8101:80"  # Toujours le port 8101, même en prod
    depends_on:
      - php  # Garde pour garantir le bon démarrage
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro